name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install root deps
        run: npm install

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
          cd ..

      - name: Install Capacitor Android
        run: |
          npm install @capacitor/cli @capacitor/core @capacitor/android
          npx cap sync android

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: gamebet-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
